### ISSUE TITLE
Пояснение

### ISSUE THREAD

**Issue by d-m-developer** [SlobodinMaxim/TGK2.TestTasks#2]
А для чего вы используете такие конструкции?
https://github.com/SlobodinMaxim/TGK2.TestTasks/blob/c94c4ff968daada1b78b80d11098126eb3eaa2f6/Task%202.2%20queries.sql#L39-L45

**Comment by SlobodinMaxim** [comment]
1. from:  для выборки данных из объединения трёх динамических представлений и одной динамической функции с целью поиска наиболее необходимых индексов;
2. where: для фильтрации выборки по текущей базе данных и таблице Products.
