### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by d-m-developer** [SlobodinMaxim/TGK2.TestTasks#3]
https://github.com/SlobodinMaxim/TGK2.TestTasks/blob/ede579c469db2594c83d8a6a693997a0fcc21604/Task1/Task1/ListRand.cs#L11-L13
Почему это является самым лучшим способом определения публичных свойств? Есть ли какие-нибудь еще способы?

**Comment by SlobodinMaxim** [comment]
@d-m-developer
Прошу прощения, мне кажется это не лучший способ определения публичных свойств (в данном случае это даже не свойства, а поля класса).
Более правильным решением было бы определить свойства так:
`public ListNode Head { get; private set; }
public ListNode Tail { get; private set; }
public int Count { get; private set; }
`

**Comment by d-m-developer** [comment]
@SlobodinMaxim, да, верно
